// Liste large de métiers/activités professionnelles (FR)
// Utilisée par le combobox du diagnostic — filtrable au fur et à mesure de la frappe.
export const ACTIVITIES: string[] = [
  "Agence de communication",
  "Agence de voyage",
  "Agence immobilière",
  "Agence web",
  "Agent commercial",
  "Agent général d'assurance",
  "Agriculteur",
  "Ambulancier",
  "Antiquaire",
  "Architecte",
  "Architecte d'intérieur",
  "Artisan boucher",
  "Artisan boulanger",
  "Artisan chocolatier",
  "Artisan fleuriste",
  "Artisan menuisier",
  "Artisan pâtissier",
  "Artisan tapissier",
  "Assistant(e) maternel(le)",
  "Auto-école",
  "Avocat",
  "Bar / Café",
  "Bijoutier",
  "Blanchisserie / Pressing",
  "Boucherie",
  "Boulangerie",
  "Bureau d'études",
  "Cabinet comptable",
  "Cabinet d'avocats",
  "Cabinet dentaire",
  "Cabinet d'expertise comptable",
  "Cabinet de kinésithérapie",
  "Cabinet médical",
  "Cabinet vétérinaire",
  "Carreleur",
  "Carrosserie",
  "Cave à vin",
  "Centre de bien-être",
  "Centre de formation",
  "Chambres d'hôtes",
  "Charcuterie",
  "Charpentier",
  "Chauffagiste",
  "Chauffeur VTC",
  "Chirurgien-dentiste",
  "Climatisation / Froid",
  "Coach sportif",
  "Coiffeur",
  "Concessionnaire automobile",
  "Conciergerie",
  "Conseil en gestion de patrimoine",
  "Consultant",
  "Contrôle technique automobile",
  "Cordonnerie",
  "Cordonnier",
  "Couvreur",
  "Créateur de site internet",
  "Crèche",
  "Cuisiniste",
  "Débarras / Nettoyage",
  "Décorateur d'intérieur",
  "Déménageur",
  "Dentiste",
  "Dépannage à domicile",
  "Dépannage informatique",
  "Diagnostic immobilier",
  "Diététicien(ne)",
  "École de conduite",
  "École de musique",
  "Électricien",
  "Élevage",
  "Encadreur",
  "Entreprise de bâtiment",
  "Entreprise de nettoyage",
  "Entreprise de peinture",
  "Entreprise de rénovation",
  "Entreprise de sécurité",
  "Entreprise de transport",
  "Épicerie",
  "Esthéticienne",
  "Étancheur",
  "Expert-comptable",
  "Facturation médicale",
  "Ferronnier",
  "Fleuriste",
  "Formateur indépendant",
  "Garage automobile",
  "Garde d'enfants",
  "Géomètre",
  "Gîte / Location saisonnière",
  "Graphiste",
  "Hôtel",
  "Huissier de justice",
  "Imprimerie",
  "Infirmier(ère) libéral(e)",
  "Informatique / IT",
  "Installateur photovoltaïque",
  "Institut de beauté",
  "Isolation",
  "Jardinerie",
  "Kinésithérapeute",
  "Laboratoire d'analyses",
  "Location de voitures",
  "Location saisonnière",
  "Maçon",
  "Magasin de bricolage",
  "Magasin de meubles",
  "Magasin de sport",
  "Magasin de vêtements",
  "Maison d'hôtes",
  "Marketing digital",
  "Menuiserie",
  "Menuisier",
  "Métallier",
  "Miroiterie",
  "Naturopathe",
  "Nettoyage industriel",
  "Notaire",
  "Opticien",
  "Orthodontiste",
  "Orthophoniste",
  "Ostéopathe",
  "Paysagiste",
  "Peintre en bâtiment",
  "Pépiniériste",
  "Photographe",
  "Piscine / Spa",
  "Pizzeria",
  "Plaquiste",
  "Plomberie",
  "Plombier",
  "Pompes funèbres",
  "Poseur de cuisine",
  "Poseur de fenêtres",
  "Poseur de parquet",
  "Pressing",
  "Primeur",
  "Producteur local",
  "Psychologue",
  "Ramonage",
  "Réflexologue",
  "Restaurant",
  "Restaurant gastronomique",
  "Restaurant rapide",
  "Salle de sport",
  "Salon de beauté",
  "Salon de coiffure",
  "Salon de tatouage",
  "Salon de thé",
  "Sellier",
  "Serrurier",
  "Serrurier-métallier",
  "Snack / Fast-food",
  "Sophrologue",
  "SPA / Institut",
  "Station-service",
  "Studio d'enregistrement",
  "Studio photo",
  "Syndic de copropriété",
  "Tabac / Presse",
  "Tapissier",
  "Taxi",
  "Toiletteur canin",
  "Traiteur",
  "Transport de marchandises",
  "Transport de personnes",
  "Travaux publics",
  "Vétérinaire",
  "Vitrier",
  "Zinguerie",
];